services:
  graphdb:
    image: sloanelab/graphdb:1.1
    ports:
      - "7200:7200"
    networks:
      - SloaneLab

  metaphactory:
    image: sloanelab/metaphactory:1.3
    ports:
      - "10220:8080"
    networks:
      - SloaneLab
    depends_on:
      - graphdb

networks:
  SloaneLab:
    driver: bridge
